core/urls.py
# from django.contrib import admin
from django.urls import path, include

from core import views
from django.contrib.auth import views as auth_views

# from django.conf import settings


urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),  # LOGIN
    path('accounts/logout', views.logout_view, name='logout'),  # LOGOUT
    path('accounts/editar/perfil', views.edit_user, name='edit_user'),  # edit_user
    path('accounts/editar/empresa', views.edit_empresa, name='edit_empresa'),  # edit_empresa


    #REETAR SENHA
    path('password_reset', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path('', views.home, name='home'),  # HOME

    path('cadastrar_usuario', views.cadastrar_usuario, name='cadastrar_usuario'),

    path('clientes', views.clientes, name='clientes'),
    path('cliente/delete/<id>', views.cliente_delete, name='cliente_delete'),

    path('quartos', views.quartos, name='quartos'),
    path('quarto/edit/<id>', views.quarto_edit, name='quarto_edit'),
    path('quarto/delete/<id>', views.quarto_delete, name='quarto_delete'),

    path('produtos', views.produtos, name='produtos'),
    path('produto/delete/<id>', views.produto_delete, name='produto_delete'),
    path('produto/edit/<id>', views.produto_edit, name='produto_edit'),


    path('reservar', views.reservar, name='reservar'),
    # path('reservando_dados/<id>', views.reservando_dados, name='reservando_dados'),
    path('disponibilidade/', views.disponibilidade, name='disponibilidade'),
    path('hospedagem/delete/<id>', views.hospedagem_delete, name='hospedagem_delete'),

    path('hospedagem/checkin/<id>', views.hospedagem_checkin, name='hospedagem_checkin'),
    path('hospedagem/checkout/<id>', views.fechar_conta_checkout, name='fechar_conta_checkout'), #checkout
    path('hospedagem/concluir/<id>', views.hospedagem_concluir, name='hospedagem_concluir'), #checkout
    path('hospedagem/editar/<id>', views.hospedagem_edit, name='hospedagem_edit'),



    path('comandas', views.comandas, name='comandas'),
    path('comanda/hospedagem/<id>', views.itenscomanda, name='itenscomanda'),
    path('comanda/produto/delete/<idcomandaconsumo>/<idhospede>', views.comanda_produto_delete,name='comanda_produto_delete'),

    

    

    path('<path:unknown_path>', views.home),

]

'''if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()'''

pousadaeasy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Hospedado(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    nome_hospede = models.CharField(max_length=200)
    habilitado = models.BooleanField(default=True)
    status = models.CharField(max_length=200, default='reservado')
    numero_quarto = models.CharField(max_length=200)
    valor_quarto = models.FloatField()
    valor_comanda = models.FloatField()
    diarias = models.IntegerField()
    data_reserva = models.DateTimeField(default=timezone.now)
    data_entrada = models.DateField()
    data_saida = models.DateField()

    def dt_reserva(self):
        self.data_reserva = timezone.now()
        self.save()


class Quarto(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    numero = models.IntegerField()
    tipo = models.CharField(max_length=200)
    capacidade = models.IntegerField(default=0)
    descricao = models.CharField(max_length=200, default="")

    def criacao(self):
        self.data_criacao = timezone.now()
        self.save()


class Endereco(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    cep = models.CharField(max_length=200)
    rua = models.CharField(max_length=200)
    complemento = models.CharField(max_length=200)
    cidade = models.CharField(max_length=200)
    estado = models.CharField(max_length=200)
    pais = models.CharField(max_length=200, default="Brasil")


class Hospede(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    nome = models.CharField(max_length=200)
    sexo = models.CharField(max_length=200, default="Não Informado")
    data_aniversario = models.DateField()
    cpf = models.CharField(max_length=200, default="null")
    rg = models.CharField(max_length=200, default="null")
    telefone = models.CharField(max_length=200, default="null")
    email = models.CharField(max_length=200, default="null")
    endereco = models.ForeignKey(Endereco, on_delete=models.PROTECT)


class Reserva(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateField(default=timezone.now)
    quarto = models.ForeignKey(Quarto, on_delete=models.PROTECT)
    habilitado = models.BooleanField(default=True)
    quantidade_hospedes = models.IntegerField(default=1)
    data_entrada = models.DateField(blank=True, null=False)
    data_saida = models.DateField(blank=True, null=False)
    diarias = models.IntegerField()
    valor = models.FloatField(default=0)


class Reserva_pendente(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    data_entrada = models.DateField(blank=True, null=False)
    quantidade_hospedes = models.IntegerField(default=0)
    data_saida = models.DateField(blank=True, null=False)
    diarias = models.IntegerField(default=0, blank=True, null=False)


class Hospedes_reserva(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    habilitado = models.BooleanField(default=True)
    data_criacao = models.DateTimeField(default=timezone.now)
    reserva = models.ForeignKey(Reserva, on_delete=models.PROTECT)
    hospede = models.ForeignKey(Hospede, on_delete=models.PROTECT)
    status = models.CharField(max_length=200, default="EM ABERTO")
    valor_comanda = models.FloatField(default=0)
    valor_total = models.FloatField(default=0)


class Produto(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    nome = models.CharField(max_length=200)
    valor_venda = models.FloatField(default=0)
    valor_custo = models.FloatField(default=0)
    descricao = models.CharField(max_length=200)


class Comanda_consumo(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    hospedes_reserva = models.ForeignKey(Hospedes_reserva, on_delete=models.PROTECT)
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)


class Fechamento_conta(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(default=timezone.now)
    habilitado = models.BooleanField(default=True)
    hospedes_reserva = models.ForeignKey(Hospedes_reserva, on_delete=models.PROTECT)
    pago = models.BooleanField(default=False)
    valor_consumo = models.FloatField()
    valor_diarias = models.FloatField()
    desconto_conta = models.FloatField()
    descricao_extra = models.TextField(max_length=2000)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, ReadOnlyPasswordHashField
from django.contrib.auth.models import User

'''
class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
        )


    def save(self, commit=True):
        user = super(EditProfileForm, self).save(commit=False)
        #user.username = self.cleaned_data['email']
        if commit:
            user.save()
        return user
        
'''
    



from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User

class EditarUsuarioForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
        labels = {
            'username': 'Nome de usuário',
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'email': 'Endereço de email',
            #'is_active': 'Conta ativa',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }



from django.contrib.auth.forms import PasswordChangeForm

class PasswordChangeCustomForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Senha antiga'}),
        label='Senha antiga'
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nova senha'}),
        label='Nova senha'
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmação de senha'}),
        label='Confirmação de senha'
    )

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

core/templates/core/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:300,400,600">

    <link rel="stylesheet" type="text/css" href="{% static 'style_cadastro.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <title>Cadastro de usuários</title>
</head>

<body>
<div class="container">
    <main class="login-form">
        <div class="cotainer">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}

                                <h5> Cadastro de Usuário</h5>

                                <div class="form-group row">
                                    {{ form_usuario.username.errors }}
                                    <label class="col-md-4 col-form-label text-md-right">Username:</label>
                                    {{ form_usuario.username }}
                                </div>

                                <div class="form-group row">
                                    {{ form_usuario.password1.errors }}
                                    <label class="col-md-4 col-form-label text-md-right">Senha:</label>
                                    {{ form_usuario.password1 }}
                                </div>

                                <div class="form-group row">
                                    {{ form_usuario.password2.errors }}
                                    <label class="col-md-4 col-form-label text-md-right">Confirmar senha:</label>
                                    {{ form_usuario.password2}}
                                </div>

                                <div class="col-md-6 offset-md-4">
                                    <div class="row">
                                        <input type="submit" value="Cadastrar" class="btn btn-primary"/>
                                    </div>
                                </div>
                            </form>
                            <a class="btn btn-outline-danger" type="button" href="{% url 'home' %}">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>
</html>

core/templates/core/clientes.html
{% extends 'base/base.html' %}

{%block content%}
<style>
    table, th {
      font-size: 14px;
    }
    table, td {
      font-size: 14px;
    }
</style>

<div class="container" style="margin-top: 50px;">
    <!-- Modal -->
    <div class="modal fade" id="modalcadastrocliente" tabindex="-1" aria-labelledby="modalcadastroclienteLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalcadastroclienteLabel">Cadastro de novo Cliente</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" class="form-inline">
                    {% csrf_token %}
                    <div class="modal-body"> <!-- INICIO modal-body-->

                        <div class="row col-md-12"> <!-- INICIO NOME-->
                            <label for="nome" class="form-label">Nome:</label>
                            <input type="text" id="nome" name="nome" class="form-control " placeholder="Nome do cliente"
                                required autofocus>
                        </div> <!-- FIM NOME-->

                        <div class="row"><!-- INICIO cpf e rg-->
                            <div class="col-md-6">
                                <label for="cpf" class="form-label espaco_abaixo">CPF:</label>
                                <input type="text" id="cpf" name="cpf" class="form-control" required>
                            </div>
                            <div class="col-md-6">
                                <label for="rg" class="form-label espaco_abaixo">RG:</label>
                                <input type="text" id="rg" name="rg" class="form-control" required>
                            </div>
                        </div> <!-- fim cpf e rg-->

                        <div class="row"> <!-- inicio aniversario e sexo-->
                            <div class="col-md-6">
                                <label for="data_aniversario" class="form-label espaco_abaixo">Data de Aniversário</label>
                                <input type="date" id="data_aniversario" name="data_aniversario" class="form-control"
                                    required>
                            </div>
                            <div class="col-md-6">
                                <label for="sexo" class="form-label espaco_abaixo">Sexo:</label>
                                <select id="sexo" name="sexo" class="form-control" required>
                                    <option value="" disabled selected>Selecione o sexo</option>
                                    <option value="femi">Feminino</option>
                                    <option value="masc">Masculino</option>
                                    <option value="mt">Outro</option>
                                    <option value="mt">Não Informado</option>
                                </select>
                            </div>
                        </div> <!-- fim aniversario e sexo-->

                        <div class="row col-md-12"> <!-- inicio email-->
                            <label for="email" class="form-label espaco_abaixo">E-mail</label>
                            <input type="email" id="email" name="email" class="form-control"
                                placeholder="E-mail do cliente">
                        </div> <!-- FIM-->

                        <div class="row col-md-12"> <!-- inicio telefone-->
                            <label for="telefone" class="form-label espaco_abaixo">Telefone</label>
                            <input type="phone" id="telefone" name="telefone" class="form-control"
                                placeholder="Telefone do cliente" required>
                        </div>

                        <div class="row"> <!-- INICIO CEP, CIDADE E ESTAO-->
                            <div class="col-md-4">
                                <label for="cep" class="form-label espaco_abaixo">CEP:</label>
                                <input type="text" id="cep" name="cep" class="form-control" required>
                            </div>
                            <div class="col-md-4">
                                <label for="cidade" class="form-label espaco_abaixo">Cidade:</label>
                                <input type="text" id="cidade" name="cidade" class="form-control" required>
                            </div>
                            <div class="col-md-4">
                                <label for="estado" class="form-label espaco_abaixo">Estado:</label>
                                <select name="estado" id="estado" name="estado" class="form-control" required>
                                    <option value="" disabled selected>Estado</option>
                                    <option value="to">TO</option>
                                    <option value="ac">AC</option>
                                    <option value="al">AL</option>
                                    <option value="ap">AP</option>
                                    <option value="am">AM</option>
                                    <option value="ba">BA</option>
                                    <option value="ce">CE</option>
                                    <option value="df">DF</option>
                                    <option value="es">ES</option>
                                    <option value="go">GO</option>
                                    <option value="ma">MA</option>
                                    <option value="mt">MT</option>
                                    <option value="ms">MS</option>
                                    <option value="mg">MG</option>
                                    <option value="pa">PA</option>
                                    <option value="pb">PB</option>
                                    <option value="pr">PR</option>
                                    <option value="pe">PE</option>
                                    <option value="pi">PI</option>
                                    <option value="rj">RJ</option>
                                    <option value="rn">RN</option>
                                    <option value="rs">RS</option>
                                    <option value="ro">RO</option>
                                    <option value="rr">RR</option>
                                    <option value="sc">SC</option>
                                    <option value="sp">SP</option>
                                    <option value="se">SE</option>
                                    <option value="to">TO</option>
                                </select>
                            </div>
                        </div> <!-- FIM CEP, CIDADE E ESTAO-->

                        <div class="row"> <!-- INICIO -->
                            <div class="col-md-6">
                                <label for="endereco" class="form-label espaco_abaixo">Logradouro:</label>
                                <input type="text" id="endereco" name="endereco" class="form-control"
                                    placeholder="Rua 00, alam 00, n 0">
                            </div>
                            <div class="col-md-6">
                                <label for="complemento" class="form-label espaco_abaixo">Complemento:</label>
                                <input type="text" id="complemento" name="complemento" class="form-control"
                                    placeholder="Referência do Endereço">
                            </div>
                        </div>
                    </div> <!-- FIM modal-body-->

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <h1 class="titulo_centro">Clientes Cadastrados</h1>

    <div class="row">
        <div class="col-md-6">
            <form method="get" id="search-form" class="form-inline">
                <div class="input-group mb-3">
                    <input class="form-control" type="search" name="search" id="search" placeholder="Buscar Cliente"
                        aria-label="Buscar"/>
                    <button class="btn btn-outline-success" id="search" type="submit">buscar</button>
                </div>
            </form>
        </div>
        <div class="col-md-5"></div>
        <div class="col-md-1">
            <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalcadastrocliente">+Cliente
            </button>
        </div>

        <div class="row">
            <table class="table" style="background-color:honeydew;" id="tabela-produtos">
                <thead>
                <tr>
                    <th class="ordenavel">Nome:</th>
                    <th class="ordenavel">CPF:</th>
                    <th class="ordenavel">RG:</th>
                    <th class="ordenavel">Telefone:</th>
                    <th class="ordenavel">e-mail</th>
                    <th class="ordenavel">Aniversario:</th>
                    <th class="ordenavel">Cidade</th>
                    <th>#</th>
                </tr>
                </thead>
                <tbody>
                {% for item in hospedes %}
                <tr>
                    <td style="white-space: nowrap;">{{ item.nome }}</td>
                    <td style="white-space: nowrap;">{{ item.cpf }}</td>
                    <td style="white-space: nowrap;">{{ item.rg }}</td>
                    <td style="white-space: nowrap;">{{ item.telefone }}</td>
                    <td style="white-space: nowrap;">{{ item.email }}</td>
                    <td style="white-space: nowrap;">{{ item.data_aniversario }}</td>
                    <td style="white-space: nowrap;">{{ item.endereco.cidade }}/{{ item.endereco.estado }}</td>
                    <td style="white-space: nowrap;">
                        <!--<a type="button" class="far fa-trash-alt" href="/cliente/delete/{{item.id}}"
                        style="font-size:20px; color:#FF0000"></a> -->
                        <a type="button" style="font-size: 12px;" class="btn btn-outline-danger" href="/cliente/delete/{{item.id}}">
                            <span class="far fa-trash-alt"></span> Excluir</a>

                        <a type="button" style="font-size: 12px;" class="btn btn-outline-primary" href="#">Editar</a>
                        
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
    {% endblock %}

core/templates/core/confirmar_delete.html
{% extends 'base/base.html' %}

{%block content%}
    <div class="container" style="margin-top: 100px;">
        <div class="container">
            <br>
            <br>	
            <br>
            <form method="post" class="form-control text-center">
                {% csrf_token %}
                <h1>Confirmar exclusão {{ item }}</h1>
                <br>
                <a type="button" class="btn btn-secondary" href="/{{pagina_redirect}}/" style="width: 100px">Cancelar</a>

                <button type="submit" class="btn btn-outline-success" style="width: 100px">Sim</button>       		
            </form>
        </div>
    </div>
    
{% endblock %}

core/templates/core/itenscomanda.html
{% extends 'base/base.html' %}
{% load humanize %}

{% block content %}
    <style>
        .container2 {
        padding: 10px;
        background-color: #f2f2f2;
        max-width: auto;
        margin: auto;
        border-radius: 5px;
        margin-top: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }
        .card {
        width: 300px;
        height: 200px;
        background-color: wheat;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        border-radius: 10px;
        padding: 10px;
        margin: 10px;
        }
        .col-md-3 {
        padding: 5px;
        }
        
        h3 {
        text-align: center;
        font-family: Georgia, 'Times New Roman', Times, serif;
        }
        .titulo {
        margin-top: 10px;
        }
        .form-cor {
        background-color: #7a8fcabe;
        }

    </style>
    <div class="container" style="margin-top: 100px;">
        <div class="titulo">
            <h3>Controle de comanda por Quarto</h3>
        </div>

        <div class="container2">
            <div class="row">
                <div class="col-md-6">
                    <p for="nome">
                        <strong>Nome:</strong> {{ hospede_reserva.hospede.nome }}
                    </p>
                    <p for="email">
                        <strong>E-mail:</strong> {{ hospede_reserva.hospede.email }}
                    </p>
                    <p for="telefone">
                        <strong>Telefone:</strong> {{ hospede_reserva.hospede.telefone }}
                    </p>
                    <p for="quarto">
                        <strong>Quarto:</strong> {{ hospede_reserva.reserva.quarto.numero }} - {{ hospede_reserva.reserva.quarto.tipo }}
                    </p>
                </div>

                <div class="col-md-6">
                    <p for="checkin">
                        <strong>Check-in:</strong> {{ hospede_reserva.reserva.data_entrada }}
                    </p>
                    <p for="checkout">
                        <strong>Check-out:</strong> {{ hospede_reserva.reserva.data_saida }}
                    </p>
                    <p for="diarias">São {{ hospede_reserva.reserva.diarias }} Diária(s) Para 
                        {{ hospede_reserva.reserva.quantidade_hospedes }} hospede(s)</p>
                    <p for="valor_hospedagem">
                        <strong>Valor da Hospedagem:</strong> R${{ hospede_reserva.reserva.valor|intcomma }}
                    </p>
                </div>
            </div>
        </div>

        <div class="container2">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-sm-5">
                        <select class="form-select form-cor" id="id_produto" name="id_produto" required>
                            <option value="" align="center" disabled selected>Selecione o Produto</option>
                            {% for produto in produtos %}
                            <option value="{{ produto.id }}">{{ produto.nome }} - R${{ produto.valor_venda }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-sm-1">
                        <input class="form-control form-cor" type="number" name="quantidade" id="quantidade" min="0" required/>
                    </div>
                    <div class="col-sm-2">
                        <button class="btn btn-primary" type="submit">Adicionar</button>
                    </div>

                    <div class="col-sm-4 text-end">
                        <a class="btn btn-success" type="button" href="{% url 'produtos' %}">+Produtos</a>
                    </div>
                </div>
            </form>
        </div><br/>

        <div id="linha_horizontal"></div>
        <div id="linha_horizontal"></div>

        <div class="row">
            <table class="table table-striped" id="tabela-produtos">
                <thead>
                <tr>
                    <th class="ordenavel">#</th>
                    <th class="ordenavel text-center">Data/Horas</th>
                    <th class="ordenavel">Nome</th>
                    <th class="ordenavel">Descrição</th>
                    <th class="ordenavel text-center">Valor</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                {% for indice, item in produtos_comanda %}
                <tr>
                    <td>{{indice}}</td>
                    <td class="text-center">{{ item.data_criacao }}</td>
                    <td>{{ item.produto.nome }}</td>
                    <td>{{ item.produto.descricao }}</td>
                    <td class="text-center">{{ item.produto.valor_venda|intcomma }}</td>
                    <td>
                        <a type="button" class="btn btn-outline-danger" href="/comanda/produto/delete/{{ item.id }}/{{ hospede_reserva.id }}">
                            <span class="far fa-trash-alt"></span>Excluir</a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <th class="text-end">Valor Total: R$ {{valor_comanda|intcomma}}</th>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}